import Provider from '@/SessionProvider'
import './globals.css'
import Navbar from '@/components/Navbar'
import TopNavbar from '@/components/TopNavbar'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

      <Provider>
        <TopNavbar />
        <Navbar />
      {children}

      </Provider>
      </body>
    </html>
  )
}
